package com.gestionhumana.demo.modelo.enumeracion;

public enum Cargo {
    AUXILIAR, PROFESIONAL_DE_APOYO, COORDINADOR, JEFE_DE_AREA, DIRECTOR_DE_AREA,
    DIRECTOR_DE_PROGRAMA, PROFESOR, PROFESOR_ADMINISTRATIVO, SUPERVISOR, DIRECTOR, CONTRATISTA
}
